
########### install files ###############

install(
    FILES
    klineedit.png
    kfontrequester.png
    kurlrequester.png
    kcombobox.png
    kled.png
    ksqueezedtextlabel.png
    kurllabel.png
    kdoublenuminput.png
    klistbox.png
    kactivelabel.png
    kiconbutton.png
    kcolorcombo.png
    khsselector.png
    kcolorbutton.png
    kpushbutton.png
    kcalendarwidget.png
    kdialog.png
    keditlistbox.png
    khistorycombo.png
    kintnuminput.png
    krestrictedline.png
    ktextedit.png
    kurlcomborequester.png
    kactionselector.png
    DESTINATION ${KDE4_DATA_INSTALL_DIR}/kdewidgets/pics
)
